server:
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?ssl=false
    username: postgres
    password: password
    hikari:
      initialization-fail-timeout: 30000

  #  jpa:
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    mapper:
      accept-case-insensitive-enums: true