server:
  port: 8081

  error:
    include-stacktrace: never
    include-exception: false
    whitelabel.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_api?ssl=false
    username: spring_boot_api
    password: password
    hikari:
      initialization-fail-timeout: 30000

  #  jpa:
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    mapper:
      accept-case-insensitive-enums: true

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: AppRealm
  public-client: true
  resource: login-app
  principal-attribute: preferred_username
