server:
  port: 8081

  error:
    include-stacktrace: never
    include-exception: false
    whitelabel.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_api?ssl=false
    username: spring_boot_api
    password: password
    hikari:
      initialization-fail-timeout: 30000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: AppRealm
  public-client: true
  resource: login-app
  principal-attribute: preferred_username

spring-boot-api:
  keycloak:
    client:
      id: spring-boot-api
      secret: o4sIaCVBkbEWiWmnKlXwM3H5QeMMK0Vf
    role-id: c389c85c-3c9a-447a-9506-e297ad0971e5
