version: "3.8"

services:

  postgres:
    image: postgres:14.2
    container_name: postgres
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/create-dbs-and-users.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=UTC

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/realm-export.json

  spring-boot-api:
    build: ..
    container_name: spring-boot-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_boot_api?ssl=false
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
